// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: pkg/pb/data_service/data_service.proto

package data_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Identifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier.ProtoReflect.Descriptor instead.
func (*Identifier) Descriptor() ([]byte, []int) {
	return file_pkg_pb_data_service_data_service_proto_rawDescGZIP(), []int{0}
}

func (x *Identifier) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *Identifier            `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Encoding      string                 `protobuf:"bytes,3,opt,name=encoding,proto3" json:"encoding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pkg_pb_data_service_data_service_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetIdentifier() *Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

type StartStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartStreamRequest) Reset() {
	*x = StartStreamRequest{}
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStreamRequest) ProtoMessage() {}

func (x *StartStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStreamRequest.ProtoReflect.Descriptor instead.
func (*StartStreamRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_data_service_data_service_proto_rawDescGZIP(), []int{2}
}

type StartStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamUuid    string                 `protobuf:"bytes,1,opt,name=stream_uuid,json=streamUuid,proto3" json:"stream_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartStreamResponse) Reset() {
	*x = StartStreamResponse{}
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStreamResponse) ProtoMessage() {}

func (x *StartStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStreamResponse.ProtoReflect.Descriptor instead.
func (*StartStreamResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_data_service_data_service_proto_rawDescGZIP(), []int{3}
}

func (x *StartStreamResponse) GetStreamUuid() string {
	if x != nil {
		return x.StreamUuid
	}
	return ""
}

type ConfigureStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamUuid    string                 `protobuf:"bytes,1,opt,name=stream_uuid,json=streamUuid,proto3" json:"stream_uuid,omitempty"`
	Identifiers   []*Identifier          `protobuf:"bytes,2,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureStreamRequest) Reset() {
	*x = ConfigureStreamRequest{}
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureStreamRequest) ProtoMessage() {}

func (x *ConfigureStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureStreamRequest.ProtoReflect.Descriptor instead.
func (*ConfigureStreamRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_data_service_data_service_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureStreamRequest) GetStreamUuid() string {
	if x != nil {
		return x.StreamUuid
	}
	return ""
}

func (x *ConfigureStreamRequest) GetIdentifiers() []*Identifier {
	if x != nil {
		return x.Identifiers
	}
	return nil
}

type ConfigureStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureStreamResponse) Reset() {
	*x = ConfigureStreamResponse{}
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureStreamResponse) ProtoMessage() {}

func (x *ConfigureStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureStreamResponse.ProtoReflect.Descriptor instead.
func (*ConfigureStreamResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_data_service_data_service_proto_rawDescGZIP(), []int{5}
}

type StopStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamUuid    string                 `protobuf:"bytes,1,opt,name=stream_uuid,json=streamUuid,proto3" json:"stream_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopStreamRequest) Reset() {
	*x = StopStreamRequest{}
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStreamRequest) ProtoMessage() {}

func (x *StopStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStreamRequest.ProtoReflect.Descriptor instead.
func (*StopStreamRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_data_service_data_service_proto_rawDescGZIP(), []int{6}
}

func (x *StopStreamRequest) GetStreamUuid() string {
	if x != nil {
		return x.StreamUuid
	}
	return ""
}

type StopStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopStreamResponse) Reset() {
	*x = StopStreamResponse{}
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStreamResponse) ProtoMessage() {}

func (x *StopStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStreamResponse.ProtoReflect.Descriptor instead.
func (*StopStreamResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_data_service_data_service_proto_rawDescGZIP(), []int{7}
}

type ConnectStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamUuid    string                 `protobuf:"bytes,1,opt,name=stream_uuid,json=streamUuid,proto3" json:"stream_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectStreamRequest) Reset() {
	*x = ConnectStreamRequest{}
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectStreamRequest) ProtoMessage() {}

func (x *ConnectStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_data_service_data_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectStreamRequest.ProtoReflect.Descriptor instead.
func (*ConnectStreamRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_data_service_data_service_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectStreamRequest) GetStreamUuid() string {
	if x != nil {
		return x.StreamUuid
	}
	return ""
}

var File_pkg_pb_data_service_data_service_proto protoreflect.FileDescriptor

const file_pkg_pb_data_service_data_service_proto_rawDesc = "" +
	"\n" +
	"&pkg/pb/data_service/data_service.proto\x12\fdata_service\"\x1e\n" +
	"\n" +
	"Identifier\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"y\n" +
	"\aMessage\x128\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x18.data_service.IdentifierR\n" +
	"identifier\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1a\n" +
	"\bencoding\x18\x03 \x01(\tR\bencoding\"\x14\n" +
	"\x12StartStreamRequest\"6\n" +
	"\x13StartStreamResponse\x12\x1f\n" +
	"\vstream_uuid\x18\x01 \x01(\tR\n" +
	"streamUuid\"u\n" +
	"\x16ConfigureStreamRequest\x12\x1f\n" +
	"\vstream_uuid\x18\x01 \x01(\tR\n" +
	"streamUuid\x12:\n" +
	"\videntifiers\x18\x02 \x03(\v2\x18.data_service.IdentifierR\videntifiers\"\x19\n" +
	"\x17ConfigureStreamResponse\"4\n" +
	"\x11StopStreamRequest\x12\x1f\n" +
	"\vstream_uuid\x18\x01 \x01(\tR\n" +
	"streamUuid\"\x14\n" +
	"\x12StopStreamResponse\"7\n" +
	"\x14ConnectStreamRequest\x12\x1f\n" +
	"\vstream_uuid\x18\x01 \x01(\tR\n" +
	"streamUuid2\x99\x02\n" +
	"\x12DataServiceControl\x12R\n" +
	"\vStartStream\x12 .data_service.StartStreamRequest\x1a!.data_service.StartStreamResponse\x12O\n" +
	"\n" +
	"StopStream\x12\x1f.data_service.StopStreamRequest\x1a .data_service.StopStreamResponse\x12^\n" +
	"\x0fConfigureStream\x12$.data_service.ConfigureStreamRequest\x1a%.data_service.ConfigureStreamResponse2d\n" +
	"\x14DataServiceStreaming\x12L\n" +
	"\rConnectStream\x12\".data_service.ConnectStreamRequest\x1a\x15.data_service.Message0\x01BMZKgitlab.michelsen.id/phillmichelsen/tessera/pkg/pb/data_service;data_serviceb\x06proto3"

var (
	file_pkg_pb_data_service_data_service_proto_rawDescOnce sync.Once
	file_pkg_pb_data_service_data_service_proto_rawDescData []byte
)

func file_pkg_pb_data_service_data_service_proto_rawDescGZIP() []byte {
	file_pkg_pb_data_service_data_service_proto_rawDescOnce.Do(func() {
		file_pkg_pb_data_service_data_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_data_service_data_service_proto_rawDesc), len(file_pkg_pb_data_service_data_service_proto_rawDesc)))
	})
	return file_pkg_pb_data_service_data_service_proto_rawDescData
}

var file_pkg_pb_data_service_data_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_pb_data_service_data_service_proto_goTypes = []any{
	(*Identifier)(nil),              // 0: data_service.Identifier
	(*Message)(nil),                 // 1: data_service.Message
	(*StartStreamRequest)(nil),      // 2: data_service.StartStreamRequest
	(*StartStreamResponse)(nil),     // 3: data_service.StartStreamResponse
	(*ConfigureStreamRequest)(nil),  // 4: data_service.ConfigureStreamRequest
	(*ConfigureStreamResponse)(nil), // 5: data_service.ConfigureStreamResponse
	(*StopStreamRequest)(nil),       // 6: data_service.StopStreamRequest
	(*StopStreamResponse)(nil),      // 7: data_service.StopStreamResponse
	(*ConnectStreamRequest)(nil),    // 8: data_service.ConnectStreamRequest
}
var file_pkg_pb_data_service_data_service_proto_depIdxs = []int32{
	0, // 0: data_service.Message.identifier:type_name -> data_service.Identifier
	0, // 1: data_service.ConfigureStreamRequest.identifiers:type_name -> data_service.Identifier
	2, // 2: data_service.DataServiceControl.StartStream:input_type -> data_service.StartStreamRequest
	6, // 3: data_service.DataServiceControl.StopStream:input_type -> data_service.StopStreamRequest
	4, // 4: data_service.DataServiceControl.ConfigureStream:input_type -> data_service.ConfigureStreamRequest
	8, // 5: data_service.DataServiceStreaming.ConnectStream:input_type -> data_service.ConnectStreamRequest
	3, // 6: data_service.DataServiceControl.StartStream:output_type -> data_service.StartStreamResponse
	7, // 7: data_service.DataServiceControl.StopStream:output_type -> data_service.StopStreamResponse
	5, // 8: data_service.DataServiceControl.ConfigureStream:output_type -> data_service.ConfigureStreamResponse
	1, // 9: data_service.DataServiceStreaming.ConnectStream:output_type -> data_service.Message
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_pb_data_service_data_service_proto_init() }
func file_pkg_pb_data_service_data_service_proto_init() {
	if File_pkg_pb_data_service_data_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_data_service_data_service_proto_rawDesc), len(file_pkg_pb_data_service_data_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_pb_data_service_data_service_proto_goTypes,
		DependencyIndexes: file_pkg_pb_data_service_data_service_proto_depIdxs,
		MessageInfos:      file_pkg_pb_data_service_data_service_proto_msgTypes,
	}.Build()
	File_pkg_pb_data_service_data_service_proto = out.File
	file_pkg_pb_data_service_data_service_proto_goTypes = nil
	file_pkg_pb_data_service_data_service_proto_depIdxs = nil
}
